### ISSUE TITLE
Add media images where media is presented

### ISSUE THREAD

**Issue by mynameiswillporter** [jhoporter/mymedialist#3]
Currently the media list and media show only displays the media title and the media release year.  The database already has a slot for the media image, however this is neither populated nor displayed on media#index or media#show.

**Comment by jhoporter** [comment]
How about we finish issue #1 and add more titles then add media images?

**Comment by mynameiswillporter** [comment]
I would prefer to add the images first, to make sure that our current db model is sufficent before we import more data.

**Comment by jhoporter** [comment]
Understood.
