### ISSUE TITLE
Make A Homepage

### ISSUE THREAD

**Issue by jhoporter** [jhoporter/mymedialist#4]
Every time we go to / it always shows the "You're on Rails!" page. Let's add a Pages controller so we can add a home action and view.

**Comment by mynameiswillporter** [comment]
Added in https://github.com/jhoporter/mymedialist/commit/a3a2ce484998ad7b8a7520ac121e2ff420ddeb73

**Comment by jhoporter** [comment]
Homepage has been added by generating a Pages controller.
